import type { Metadata } from 'next'
import { Check, CircleHelp, Clock3, MessageCircle, Plane, X } from 'lucide-react'
import { CmsBlocks } from '../../_components/cms-blocks'
import { RouteMap } from '../../_components/decorations'
import { PageShell } from '../../_components/site'
import { Button, Card, Heading, Section } from '../../_components/ui'
import { getPageBySlug } from '../../page-data'

export const metadata: Metadata = { title: 'Letadlem s miminkem a malými dětmi | Furt někde', description: 'Praktický online kurz pro rodiče, kteří se chtějí připravit na let s miminkem nebo malým dítětem.', robots: { index: false, follow: false } }
const slug = 'kurzy/letadlem-s-miminkem-a-malymi-detmi'

export default async function FlightCoursePage() {
  const foundPage = await getPageBySlug(slug)
  const page = foundPage?.pageType === 'course' ? foundPage : undefined
  const price = page?.coursePrice ?? 1390
  const hasCmsLayout = Boolean(page?.layout?.length)
  return <PageShell>
    <Section className="course-hero"><div className="course-hero-grid"><div><p className="eyebrow">{page?.eyebrow || 'Online kurz · 14 praktických částí'}</p><h1>{page?.title || 'Letadlem s miminkem a malými dětmi'}</h1><p className="lead">{page?.summary || 'Připravte se na cestu krok za krokem — od výběru letu a balení až po chvíle, kdy plán nevyjde přesně podle představ.'}</p><div className="price-line"><strong>{price.toLocaleString('cs-CZ')} Kč</strong><span>jednorázově · bez splátek</span></div><Button href={page?.primaryCta?.href || '#objednavka'}>{page?.primaryCta?.label || 'Přejít k objednávce kurzu'}</Button><p className="microcopy">Tlačítko vás v tomto prototypu posune k rekapitulaci. Platba zatím není zapojená.</p></div><RouteMap compact /></div></Section>
    {hasCmsLayout ? <CmsBlocks blocks={page?.layout} /> : <>
    <Section className="outcome"><div className="narrow"><p className="eyebrow">Výsledek kurzu</p><Heading>Budete vědět, co připravit před odletem a jak postupovat během cesty</Heading><p className="large-copy">Kurz shromažďuje praktické kroky pro rozhodování před cestou, na letišti i v letadle. Neslibuje cestu bez komplikací — pomůže vám připravit se na běžné situace i změny plánu.</p></div></Section>
    <Section className="audience"><div className="two-cards"><Card className="yes-card"><Check aria-hidden="true" /><h2>Pro koho kurz je</h2><ul><li>Čeká vás let s miminkem nebo malým dítětem.</li><li>Chcete si přípravu rozdělit do zvládnutelných kroků.</li><li>Oceníte zkušenosti, odborné rady a materiály pohromadě.</li></ul></Card><Card className="no-card"><X aria-hidden="true" /><h2>Pro koho kurz není</h2><ul><li>Hledáte rezervaci letenek nebo cestovní služby na míru.</li><li>Potřebujete závazné aktuální podmínky konkrétního dopravce.</li><li>Očekáváte jistotu, že cesta proběhne bez nečekaných situací.</li></ul></Card></div></Section>
    <Section className="curriculum"><div className="section-intro"><p className="eyebrow">Co projdete</p><Heading>14 praktických částí od prvního rozhodnutí po přistání</Heading></div><ol className="module-list">{['Výběr letu a času cesty','Pravidla dopravce a co ověřit','Doklady a příprava před odletem','Balení příručního zavazadla','Výbava pro miminko a malé dítě','Cesta na letiště','Odbavení a zavazadla','Bezpečnostní kontrola','Čekání a nástup do letadla','Vzlet a změny tlaku','Jídlo a pití během cesty','Spánek a zabavení dítěte','Krizové a nečekané situace','Přistání a první kroky po letu'].map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, '0')}</span>{item}</li>)}</ol><p className="source-note">Konkrétní pravidla se mezi dopravci mění. Před cestou je vždy ověřte přímo u své letecké společnosti.</p></Section>
    <Section className="materials"><div className="section-intro"><p className="eyebrow">Součást kurzu</p><Heading>Materiály, ke kterým se můžete vracet</Heading></div><div className="benefit-grid"><Card><Clock3 /><h3>Dlouhodobý přístup</h3><p>Postupujete vlastním tempem, bez časového tlaku. Přesná technická délka přístupu bude potvrzena před finálním objednávkovým nastavením.</p></Card><Card><MessageCircle /><h3>Možnost položit otázku</h3><p>Ke kurzu můžete položit otázku. Přesný rozsah podpory a doba odpovědi budou potvrzeny před spuštěním prodeje.</p></Card><Card><Plane /><h3>Praktické podklady</h3><p>Součástí jsou vlastní zkušenosti, rady odborníků a bonusové materiály pro přípravu cesty.</p></Card></div></Section>
    <Section className="order" id="objednavka"><div className="order-card"><div><p className="eyebrow">Rekapitulace</p><Heading>Letadlem s miminkem a malými dětmi</Heading><ul className="check-list"><li>14 praktických částí</li><li>Dlouhodobý přístup bez časového tlaku</li><li>Možnost položit otázku ke kurzu</li></ul></div><div className="order-price"><strong>{price.toLocaleString('cs-CZ')} Kč</strong><span>jednorázová platba bez splátek</span><button className="button button--primary" type="button" aria-describedby="prototype-note">Přejít k objednávce kurzu</button><small id="prototype-note">Objednávka není v prototypu aktivní. K žádné platbě ani potvrzení nákupu nedojde.</small></div></div></Section>
    <Section className="faq"><div className="section-intro"><CircleHelp aria-hidden="true" /><Heading>Časté dotazy</Heading></div><div className="faq-list"><Faq question="Jak dlouho budu mít ke kurzu přístup?">Přístup je dlouhodobý a bez časového tlaku. Přesnou technickou délku ještě před finálním objednávkovým nastavením ověříme.</Faq><Faq question="Mohu ke kurzu položit otázku?">Ano. Přesný rozsah podpory a očekávanou dobu odpovědi ještě potvrdíme před spuštěním prodeje.</Faq><Faq question="Platí informace pro každou leteckou společnost?">Pravidla se mohou lišit a měnit. Aktuální podmínky zavazadel, přepravy kočárku a dalších služeb vždy ověřte přímo u svého dopravce.</Faq><Faq question="Objednám kurz už na této stránce?">Zatím ne. Jde o schvalovací prototyp; tlačítko pouze ukazuje budoucí přechod k objednávce.</Faq></div></Section>
    </>}
  </PageShell>
}

function Faq({ question, children }: { question: string; children: string }) { return <details><summary>{question}</summary><p>{children}</p></details> }
